import { esc, fmtInt, groupBy, profileOrder } from '../utils.js';
export function renderRouting(s,ui){
  const source=ui.routingMinutes===5?(s.fallback_edges_5m||[]):ui.routingMinutes===1440?(s.fallback_edges_24h||[]):(s.fallback_edges_1h||[]);
  const edges=source.filter(e=>ui.routingProfile==='all'||e.from_profile===ui.routingProfile);
  const profiles=Object.keys(groupBy(s.upstreams||[],'profile')).sort(profileOrder);
  const profCounts=profiles.map(p=>({p,req:(s.upstreams||[]).filter(u=>u.profile===p).reduce((x,u)=>x+Number(u.requests||0),0),active:(s.upstreams||[]).filter(u=>u.profile===p&&u.active).length,count:(s.upstreams||[]).filter(u=>u.profile===p).length}));
  return `<h1 class="page-title">Маршрутизация</h1><div class="toolbar"><select class="select" id="routingProfile"><option value="all">Все профили</option>${profiles.map(p=>`<option ${ui.routingProfile===p?'selected':''}>${esc(p)}</option>`).join('')}</select>${[[5,'5 мин'],[60,'1 час'],[1440,'24 часа']].map(([n,t])=>`<button class="btn ${ui.routingMinutes===n?'active':''}" data-rminutes="${n}">${t}</button>`).join('')}</div>
  <div class="two-col"><section class="panel table-panel"><div class="panel-header"><span class="panel-title">Fallback маршруты</span><span class="panel-meta">${fmtInt(edges.reduce((n,e)=>n+Number(e.count||0),0))} за период</span></div><table class="data-table"><thead><tr><th>Откуда</th><th style="width:50px"></th><th>Куда</th><th style="width:150px">Профиль</th><th style="width:150px">Срабатываний</th></tr></thead><tbody>${edges.length?edges.map(e=>`<tr><td><div class="cell-title">${esc(e.from_upstream)}</div><div class="cell-sub">:${e.from_port}</div></td><td class="metric good">→</td><td><div class="cell-title">${esc(e.to_upstream)}</div><div class="cell-sub">:${e.to_port}</div></td><td>${esc(e.from_profile)}</td><td class="metric good">${fmtInt(e.count)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Fallback переходов за выбранный период нет</td></tr>'}</tbody></table></section>
  <section class="panel"><div class="panel-header"><span class="panel-title">Профили Keenetic</span></div>${profCounts.map(x=>`<div class="info-row"><div><div class="info-label">${esc(x.p)}</div><div class="info-help">${x.count} DNS · ${x.active} active</div></div><div class="info-value" style="color:var(--color-accent);font-weight:700">${fmtInt(x.req)} req</div></div>`).join('')}</section></div>`;
}
