import { esc, fmtInt, fmtPct, fmtMs, fmtAgo, statusFor, quality, qualityClass } from '../utils.js';
export function renderServers(s,ui){
  const ups=s.upstreams||[]; if(!ups.length)return '<h1 class="page-title">Серверы</h1><div class="panel"><div class="empty">DNS серверы не обнаружены</div></div>';
  let selected=ups.find(u=>u.port===ui.serverPort)||ups[0]; ui.serverPort=selected.port;
  const list=ups.map(u=>{const st=statusFor(u);return `<button class="side-item ${u.port===selected.port?'active':''}" data-port="${u.port}"><div class="name"><span class="status-led ${st.cls==='down'?'error':st.cls==='degraded'?'warn':''}"></span>${esc(u.name)} <span class="pill accent">${esc(u.protocol)}</span></div><div class="meta">${esc(u.profile)} · ${u.port}</div></button>`}).join('');
  const st=statusFor(selected), w=selected.stats_5m||{}, q=quality(selected), flow=(s.flow||[]).filter(f=>f.port===selected.port).slice(-14).reverse();
  return `<h1 class="page-title">Серверы</h1><div class="server-layout"><div class="side-list"><div class="side-list-title">DNS серверы (${ups.length})</div>${list}</div><div>
    <div class="hero-card"><div class="hero-head"><div><div class="hero-title">${esc(selected.name)} <span class="pill accent">${esc(selected.protocol)}</span></div><div class="hero-sub">${esc(selected.profile)} · ${esc(selected.target)}</div></div><span class="pill ${st.pill}">${st.label}</span></div>
    <div class="hero-metrics"><div class="hero-metric"><b>${fmtInt(w.requests||0)}</b><span>Запросы 5m</span></div><div class="hero-metric"><b>${w.p95_latency_ms?fmtMs(w.p95_latency_ms):'—'}</b><span>P95 latency 5m</span></div><div class="hero-metric"><b>${fmtPct(w.fallback_pct||0)}</b><span>Fallback 5m</span></div><div class="hero-metric"><b class="${qualityClass(w)}">${q.toFixed(2)}%</b><span>Quality 5m</span></div></div></div>
    ${qualityPanel(selected)}
    ${diagnosticPanel(selected)}
    <div class="info-list"><div class="panel-header"><span class="panel-title">Сведения о DNS</span></div>
      ${info('Target',selected.target,'Адрес upstream resolver')}${info('Профиль',selected.profile,'Профиль DNS proxy Keenetic')}${selected.policy_mark?info('Policy route',`mark 0x${Number(selected.policy_mark).toString(16)} · table ${selected.policy_table||'—'}`,'Динамическая policy routing Keenetic'):''}${info('SNI',selected.sni||'—','TLS Server Name')}${info('Domain filter',selected.domain||'все домены','Доменная привязка resolver')}${info('Interface',selected.interface||'не задан','Исходящий интерфейс Keenetic')}${selected.linux_interface?info('Linux interface',selected.linux_interface,'Сопоставленный netdev Linux'):''}${info('Local port',String(selected.port),'Внутренний DNS proxy порт')}${info('Timeout',selected.timeout_ms?`${selected.timeout_ms} ms`:'—','Keenetic timeout')}${info('Proceed',selected.proceed_ms?`${selected.proceed_ms} ms`:'—','Порог запуска fallback')}
    </div>
    <section class="panel table-panel"><div class="panel-header"><span class="panel-title">Последние запросы</span><span class="panel-meta">${fmtAgo(selected.last_request)}</span></div><table class="data-table"><thead><tr><th style="width:110px">Время</th><th>Домен</th><th style="width:90px">Тип</th><th style="width:100px">Fallback</th></tr></thead><tbody>${flow.length?flow.map(f=>`<tr><td class="mono">${new Date(f.time).toLocaleTimeString('ru-RU')}</td><td>${esc(f.domain)}</td><td><span class="pill">${esc(f.qtype)}</span></td><td>${f.fallback?'<span class="pill warn">да</span>':'—'}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Нет live-запросов</td></tr>'}</tbody></table></section>
  </div></div>`;
}
function qualityPanel(u){const rows=[['5 минут',u.stats_5m],['1 час',u.stats_1h],['24 часа',u.stats_24h]];return `<div class="info-list"><div class="panel-header"><span class="panel-title">Качество resolver</span></div>${rows.map(([name,w])=>`<div class="info-row"><div><div class="info-label">${name}</div><div class="info-help">${fmtInt(w?.requests||0)} запросов · ${fmtInt(w?.errors||0)} DNS errors · ${fmtInt(w?.timeouts||0)} timeout</div></div><div class="info-value"><span class="metric ${qualityClass(w)}">${Number(w?.quality_pct??100).toFixed(2)}%</span> · p95 ${w?.p95_latency_ms?fmtMs(w.p95_latency_ms):'—'} · fallback ${fmtPct(w?.fallback_pct||0)}</div></div>`).join('')}</div>`}
function diagnosticPanel(u){const d=u.diagnostic||{};if(!d.ran)return `<section class="panel"><div class="panel-header"><span class="panel-title">Диагностика DoT/DoH</span><span class="panel-meta">автоматически при DOWN</span></div><div class="empty">Прямая диагностика ещё не запускалась. Она стартует автоматически, если health-check дважды подряд переведёт resolver в DOWN.</div></section>`;const cls=d.status==='FAIL'?'error':'ok';return `<section class="panel"><div class="panel-header"><span class="panel-title">Диагностика DoT/DoH</span><span class="pill ${cls}">${esc(d.status||'—')}</span></div>${info('Этап',d.stage||'—','Последний достигнутый этап')}${info('Target IP',d.target_ip||'—','IP прямой проверки')}${info('Resolve',d.resolve_ms?fmtMs(d.resolve_ms):'—','Разрешение имени upstream')}${info('TCP',d.tcp_ms?fmtMs(d.tcp_ms):'—','Установка TCP соединения')}${info('TLS',d.tls_ms?fmtMs(d.tls_ms):'—','TLS handshake')}${info(u.protocol==='DoH'?'HTTP / DNS':'DNS',d.protocol_ms?fmtMs(d.protocol_ms):'—','Протокольная проверка')}${u.protocol==='DoH'?info('HTTP status',d.http_status?String(d.http_status):'—','Ответ DoH endpoint'):''}${info('DNS RCODE',d.dns_rcode||'—','Ответ прямого DNS probe')}${diagnosticAssessment(d)}${d.default_status?info('Default route',`${d.default_status}${d.default_stage?' · '+d.default_stage:''}`,'Контрольная проверка без Policy/interface binding'):''}${info('Ошибка',d.error||'нет','Причина остановки диагностики')}${info('Последний запуск',fmtAgo(d.last_run),d.route_scope||'')}</section>`}
function info(a,b,h){return `<div class="info-row"><div><div class="info-label">${esc(a)}</div><div class="info-help">${esc(h)}</div></div><div class="info-value">${esc(b)}</div></div>`}

function diagnosticAssessment(d){
  if(d.assessment==='POLICY_ROUTE_FAIL') return info('Вывод','Policy route не проходит, default route доступен','Проблема подтверждена в таблице/mark политики Keenetic');
  if(d.assessment==='INTERFACE_ROUTE_FAIL') return info('Вывод','Маршрут через заданный интерфейс не проходит, default route доступен','Проблема привязки интерфейса');
  if(d.assessment==='UPSTREAM_OK_LOCAL_PROXY_FAIL') return info('Вывод','Policy/interface route до upstream работает; ломается локальный DNS proxy Keenetic','Маршрутная проверка успешна, а локальный health остаётся DOWN');
  if(d.assessment==='UPSTREAM_OK_LOCAL_PATH_FAIL') return info('Вывод','Upstream доступен; вероятна проблема локального DNS proxy / Policy Keenetic','Прямая проверка успешна, а локальный health-check остаётся DOWN');
  if(d.assessment==='UPSTREAM_OK') return info('Вывод','Upstream доступен напрямую','Прямая проверка завершилась успешно');
  if((d.assessment||'').startsWith('UPSTREAM_')) return info('Вывод',`Ошибка upstream на этапе ${d.stage||'—'}`,'Проблема подтверждается вне локального DNS proxy');
  return '';
}
