import { esc, fmtInt, fmtDuration, fmtAgo } from '../utils.js';
import { themes } from '../state.js';
export function renderSettings(s,ui,settings,sys){
  return `<h1 class="page-title">Настройки</h1><div class="settings-layout"><aside><div class="system-card"><div class="system-head"><span>Система</span><span class="status-line ${s.capture_error?'down':''}" style="font-size:11px">${s.capture_error?'ERROR':'OK'}</span></div>${sysrow('DNS Monitor',`v${s.version||'—'}`)}${sysrow('Статус',s.active_down?'ERROR':s.active_degraded?'DEGRADED':'OK')}${sysrow('Uptime',fmtDuration(s.uptime_seconds))}${sysrow('Upstream',fmtInt(s.upstream_count))}${sysrow('Запросы',fmtInt(s.total_requests))}${sysrow('Discovery',fmtAgo(s.last_discovery))}${sysrow('RAM',sys?.rss_kb?`${(sys.rss_kb/1024).toFixed(1)} MB`:'—')}</div></aside>
  <div class="settings-stack">
    <section class="settings-section"><div class="settings-title">⚙ Общие</div>${setting('Уровень интерфейса','Скрывает технические поля, которые не нужны при обычном использовании.',`<select class="select" id="uiLevel"><option value="normal" ${settings.uiLevel==='normal'?'selected':''}>Обычный</option><option value="expert" ${settings.uiLevel==='expert'?'selected':''}>Экспертный</option></select>`)}${setting('Ширина интерфейса','Компактная ширина фиксирует рабочую область по центру, как в роутерных панелях.',`<select class="select" id="widthMode"><option value="classic" ${!settings.compact?'selected':''}>Классическая</option><option value="compact" ${settings.compact?'selected':''}>Компактная</option></select>`)}${setting('Автообновление','Частота обновления данных интерфейса. Не влияет на DNS capture.',`<select class="select" id="refreshMs">${[1000,2000,5000,10000].map(x=>`<option value="${x}" ${settings.refreshMs===x?'selected':''}>${x/1000} сек</option>`).join('')}</select>`)}</section>
    <section class="settings-section"><div class="settings-title">🎨 Внешний вид</div><div class="theme-grid">${themeCard('legacy','DNSM · Legacy','Глубокие тёмно-синие оттенки.',settings)}${themeCard('neo','DNSM · Neo','Высокая контрастность и яркий акцент.',settings)}${themeCard('mint','DNSM · Mint','Мягкая серо-синяя палитра.',settings)}${themeCard('custom','DNSM · Custom','Три базовых цвета, остальные вычисляются.',settings)}</div>${settings.theme==='custom'?`<div class="color-row">${colorBox('Акцент','accent',settings.accent)}${colorBox('Фон','background',settings.background)}${colorBox('Текст','text',settings.text)}</div>`:''}</section>
    <section class="settings-section"><div class="settings-title">↻ Мониторинг</div>${setting('Discovery','Автоматически перечитывает DoT/DoH и Policy из Keenetic.','60 сек')}${setting('Health-check','Проверка каждого локального DNS upstream через реальный proxy.','30 сек')}${setting('История','Minute buckets хранятся только в RAM.','24 часа')}${setting('Веб-порт','Read-only панель DNS Monitor.','2233')}</section>
  </div></div>`;
}
function setting(n,d,c){return `<div class="setting-row"><div><div class="setting-name">${esc(n)}</div><div class="setting-desc">${esc(d)}</div></div><div class="setting-control">${c}</div></div>`}
function sysrow(a,b){return `<div class="system-row"><span>${esc(a)}</span><span>${esc(b)}</span></div>`}
function themeCard(id,title,desc,s){const t=themes[id]||{accent:s.accent,background:s.background,text:s.text,secondary:'#101010',tertiary:'#202020'};return `<div class="theme-card ${s.theme===id?'active':''}" data-theme-card="${id}"><h4>${esc(title)}</h4><div class="cell-sub" style="font-family:var(--font-sans);margin-bottom:7px">${esc(desc)}</div><div class="theme-preview" style="background:${t.background};color:${t.text}"><i style="width:25%;background:${t.accent}"></i><i style="width:80%;background:${t.text};opacity:.14"></i><i style="background:${t.secondary};border:1px solid ${t.tertiary}"></i></div></div>`}
function colorBox(label,key,value){return `<div class="color-box"><label>${esc(label)}</label><div class="color-control"><input type="color" data-color-key="${key}" value="${esc(value)}"><code>${esc(value)}</code></div></div>`}
