import { esc, timeOnly, fmtInt, fmtDuration, bytes } from '../utils.js';
export function renderTools(s,ui,sys){
 const tabs=['journal','connections','dns','system']; const names={journal:'Журнал',connections:'Соединения',dns:'Сведения о DNS',system:'Система'};
 const top=`<h1 class="page-title">Инструменты</h1><div class="subtabs">${tabs.map(t=>`<button class="subtab ${ui.toolTab===t?'active':''}" data-ttab="${t}">${names[t]}</button>`).join('')}</div>`;
 if(ui.toolTab==='journal') return top+journal(s,ui);
 if(ui.toolTab==='connections') return top+connections(s);
 if(ui.toolTab==='dns') return top+dnsInfo(s);
 return top+system(s,sys);
}
function journal(s,ui){
 const source=ui.logPaused?(ui.frozenErrors||[]):(s.errors||[]); let e=source.slice().reverse();
 if(ui.logKind!=='all')e=e.filter(x=>x.kind===ui.logKind);
 const q=(ui.logSearch||'').toLowerCase(); if(q)e=e.filter(x=>`${x.kind||''} ${x.profile||''} ${x.upstream||''} ${x.domain||''} ${x.message||''}`.toLowerCase().includes(q));
 const bursts=(ui.logPaused?(ui.frozenBursts||[]):(s.error_bursts||[])).slice(0,8);
 const burstPanel=bursts.length?`<section class="panel table-panel"><div class="panel-header"><span class="panel-title">Сводка ошибок за 1 час</span></div><table class="data-table"><thead><tr><th style="width:95px">Время</th><th>DNS</th><th style="width:110px">Тип</th><th style="width:90px">Кол-во</th><th>Примеры доменов</th></tr></thead><tbody>${bursts.map(b=>`<tr><td class="mono">${timeOnly(b.minute)}</td><td>${esc(b.profile)} · <b>${esc(b.upstream)}</b></td><td><span class="pill ${b.kind==='TIMEOUT'?'warn':'error'}">${esc(b.kind)}</span></td><td class="metric bad">${fmtInt(b.count)}</td><td class="cell-sub">${esc((b.domains||[]).join(', ')||'—')}</td></tr>`).join('')}</tbody></table></section>`:'';
 const live=ui.logPaused?'<span class="live-paused">ЖУРНАЛ ЗАФИКСИРОВАН</span>':'<span class="live-running">LIVE</span>';
 return `${burstPanel}<section class="panel"><div class="toolbar" style="padding:8px;margin:0">${live}<button id="journalPause" class="btn ${ui.logPaused?'active':''}">${ui.logPaused?'▶ Продолжить':'Ⅱ Пауза'}</button>${['all','SERVFAIL','TIMEOUT','DOWN','RECOVERED'].map(k=>`<button class="btn ${ui.logKind===k?'active':''}" data-logkind="${k}">${k.toUpperCase()}</button>`).join('')}<input id="logSearch" class="input" style="flex:1" placeholder="Поиск..." value="${esc(ui.logSearch||'')}"></div><div class="log-shell" data-live-flow="journal">${e.length?e.map(x=>`<div class="log-row"><span class="log-time">${timeOnly(x.time)}</span><span class="log-kind ${esc(x.kind)}">${esc(x.kind)}</span><span class="log-msg">${esc(`${x.profile||''} · ${x.upstream||''} · ${x.domain||''} — ${x.message||''}`)}</span></div>`).join(''):'<div class="empty">Событий нет</div>'}</div></section>`
}
function connections(s){return `<section class="panel table-panel"><div class="panel-header"><span class="panel-title">Локальные DNS proxy</span></div><table class="data-table"><thead><tr><th>Профиль</th><th>DNS</th><th>Протокол</th><th>Local</th><th>Target</th><th>Interface</th></tr></thead><tbody>${(s.upstreams||[]).map(u=>`<tr><td>${esc(u.profile)}</td><td class="cell-title">${esc(u.name)}</td><td><span class="pill accent">${esc(u.protocol)}</span></td><td class="mono">127.0.0.1:${u.port}</td><td class="mono">${esc(u.target)}</td><td>${esc(u.interface||'—')}</td></tr>`).join('')}</tbody></table></section>`}
function dnsInfo(s){return `<div class="two-col"><section class="panel"><div class="panel-header"><span class="panel-title">Discovery</span></div>${info('Последний discovery',s.last_discovery||'—')}${info('Discovery error',s.discovery_error||'нет')}${info('Capture error',s.capture_error||'нет')}${info('Upstream DNS',String(s.upstream_count||0))}</section><section class="panel"><div class="panel-header"><span class="panel-title">Счётчики</span></div>${info('Requests',fmtInt(s.total_requests))}${info('Responses',fmtInt(s.total_responses))}${info('Fallbacks',fmtInt(s.total_fallbacks))}${info('Active DOWN',fmtInt(s.active_down))}</section></div>`}
function system(s,sys){return `<div class="two-col"><section class="panel"><div class="panel-header"><span class="panel-title">DNS Monitor</span></div>${info('Версия',s.version||'—')}${info('Uptime',fmtDuration(s.uptime_seconds))}${info('Go runtime',sys?.go_version||'—')}${info('Архитектура',sys?.goarch||'—')}</section><section class="panel"><div class="panel-header"><span class="panel-title">Процесс</span></div>${info('RSS',bytes((sys?.rss_kb||0)*1024))}${info('VmSize',bytes((sys?.vmsize_kb||0)*1024))}${info('Goroutines',fmtInt(sys?.goroutines||0))}${info('PID',fmtInt(sys?.pid||0))}</section></div>`}
function info(k,v){return `<div class="info-row"><div class="info-label">${esc(k)}</div><div class="info-value">${esc(v)}</div></div>`}
