#!/bin/sh
ENABLED=yes
PROCS=dnsmon-system
ARGS="-module system -socket /opt/var/run/dns-monitor-system.sock"
PREARGS=""
DESC="DNS Monitor System"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /opt/etc/init.d/rc.func
