#!/bin/sh
ENABLED=yes
PROCS=routerforge-storage
ARGS="-module storage -socket /opt/var/run/routerforge-storage.sock"
PREARGS=""
DESC="RouterForge Storage Monitor"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /opt/etc/init.d/rc.func
