#!/bin/sh
mkdir -p /opt/var/run
if [ -x /opt/etc/init.d/S91dns-monitor-admin ]; then
    /opt/etc/init.d/S91dns-monitor-admin stop >/dev/null 2>&1 || true
    /opt/etc/init.d/S91dns-monitor-admin start >/dev/null 2>&1 || true
fi
exit 0
