#!/bin/sh
ENABLED=yes
PROCS=routerforge-system
ARGS="-module system -socket /opt/var/run/routerforge-system.sock"
PREARGS=""
DESC="RouterForge System Monitor"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /opt/etc/init.d/rc.func
