#!/bin/sh
ENABLED=yes
PROCS=dnsmon-admin
ARGS="-socket /opt/var/run/dns-monitor-admin.sock"
PREARGS=""
DESC="DNS Monitor Admin"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /opt/etc/init.d/rc.func
