#!/bin/sh
ENABLED=yes
PROCS=routerforge-admin
ARGS="-socket /opt/var/run/routerforge-admin.sock"
PREARGS=""
DESC="RouterForge Control"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /opt/etc/init.d/rc.func
